### PR TITLE
Choose dates

### PR DESCRIPTION
**Pull request by nmohamed**
- Filters/chooses dates better with three dropdowns (year/month/day)
- Minor edits to viewing student data otherwise
- Removed extra tab panes because they're redundant

After this I'll get to work on showing longterm data. Also, glyphcons for engagement are tentative. there's a blackboard one that can be used too. I wasn't sure what to use for peers so feedback on that one would be good

### CODE REVIEW

**Comment by BrennaManning** [comment]
:alien:

**Comment by nmohamed** [comment]
side note:
i've found the answer to whether or not you should include `;` - in short, use semicolons after _statements_/function statements (i.e., `var x =1;` or `var x = function(){};`) and not function _declarations_ (i.e., `function hi(){}` or blocks like `if(){}`)
also, always put IIEFs at the top of your code if you follow this semicolon convention, since you'll run into errors if you dont
i.e., don't do this: 

```
function hi(){}
(function(stuff){more stuff}());
```

do this

```
(function(stuff){more stuff}());
function hi(){}
```

or just add a semicolon to the end of `hi()` in the first one. really, it's better to add semicolons after everyline than to not have semicolons, although etiquette is to just have them after statements.
https://stackoverflow.com/questions/11978698/do-we-need-a-semicolon-after-function-declaration

some funny links:
https://github.com/twbs/bootstrap/issues/3057
https://github.com/isaacs/semicolons/blob/master/semicolons.js

**Comment by davidabrahams** [comment]
I'm good to merge!

@nmohamed what is an IEFF? Also what does `(function(stuff){more stuff}());` do? I assume it instantiates a function and then calls it, but I'm unsure.

Does the first case instantiate `hi` and then call it, passing the output of `function(stuff)` to it? If so, that's pretty funky. It seems like this would be a good reason to use function expressions exclusively, which I have been doing in my own code.

For those who want to know the difference:

```
function thisIsADeclaration() {
 // This is a declaration
}

var thisIsAnExpression = function() {
 // This is an expression
}; // NOTE THE SEMICOLON HERE
```

I _think_ this is the correct syntax, but please correct me if I'm wrong @nmohamed

**Comment by nmohamed** [comment]
@david, yup. there was a typo there - i meant to say IIFE (immediately invoked function expressions, which as the name implies, are immediately invoked)
and the problem with the first example is that it'll be run as 

```
function hi(){}(function(stuff){more stuff}());
```

instead of two separate functions

**Comment by aconsilvio** [comment]
👍

**Comment by shrutiyer** [comment]
:+1: :floppy_disk: :cactus: :last_quarter_moon_with_face: :hammer:

**Pull request merged**
