### PR TITLE
Relative scopes

### PR DESCRIPTION
**Pull request by davidabrahams**
I changed all the rootscope references to scope.parent. I think this is a good idea so that we don't overload rootscope with information (since rootscope is for the entire project, where as scope.parent is relative)

### CODE REVIEW

**Comment by aconsilvio** [comment]
:+1:

**Comment by nmohamed** [comment]
did you test not using rootscope? the reason i used it before was because ui-sref is not reloading the controllers. so, scope.parent wouldn't work since the controller wouldn't be reloaded for the new student

**Comment by nmohamed** [comment]
rootscope was used /because/ scope.parent didn't work

**Comment by davidabrahams** [comment]
Yes, this worked...

**Pull request closed without merging**
