### PR TITLE
EDIT: fixed #185. Theres now glyphicons that change when you click th…

### LINKED ISSUE #185: Make dropdown glyphs change

### PR DESCRIPTION
**Pull request by davidabrahams**
…e menus. Also some general sidebar improvements, like collapsing the student accordions when you hit add students. I also moved the add student button to the top

### CODE REVIEW

**Comment by nmohamed** [comment]
looks pretty :palm_tree:

**Comment by aconsilvio** [comment]
yess this looks great

**Comment by BrennaManning** [comment]
:sunflower:

**Comment by BrennaManning** [comment]
Merging!

**Pull request merged**
