### PR TITLE
Date of submission

### PR DESCRIPTION
**Pull request by BrennaManning**
Added date of submission of entry to database 
(Now includes date entry is about by input and date it was submitted automatically)

### CODE REVIEW

**Comment by davidabrahams** [comment]
Do we want to merge this or would we rather do a big database fix later?

**Comment by BrennaManning** [comment]
I don't see the harm in merging it now as it doesn't interfere with anything else and we had said we wanted it. Though a database overhaul is needed now. I would like to work on that tomorrow.

**Comment by BrennaManning** [comment]
I'm assuming we are going to follow the structure discussed before with one way ID referencing? And including all the features Bianca listed in the email tonight

**Comment by davidabrahams** [comment]
Sounds good

**Comment by aconsilvio** [comment]
I think this is basically ready to merge :)

**Comment by nmohamed** [comment]
looks good

**Pull request merged**
