### PR TITLE
EDIT: used datepicker in longterm form

### PR DESCRIPTION
**Pull request by davidabrahams**

### CODE REVIEW

**Comment by nmohamed** [comment]
since longterm has weekly, monthly, etc data, shouldn't the datepicker be choosing a time period that reflects that? i think we'll have to change it to fit the format of whatever type of date we want

**Comment by BrennaManning** [comment]
+1 to Nora's comment, though I think it's okay to have this for now? If nothing else, they could  be able to see when it was submitted

**Comment by shrutiyer** [comment]
I think we should discuss what is the best way to do it. Maybe a start date and the end date? And then cross check to make sure the time between dates matches the drop down selected

**Comment by davidabrahams** [comment]
Should we just merge this PR for now since all it does is change the widget and then make another PR later to actually make it a date range?

**Comment by davidabrahams** [comment]
Fixes #117

**Comment by aconsilvio** [comment]
👍

**Pull request merged**
