### PR TITLE
EDIT: Fixed #179. Fixed navbar to top of page

### LINKED ISSUE #179: header scolls with content of page - it's not fixed (firefox)
and doing position:fixed doesn't fix it.

### PR DESCRIPTION
**Pull request by davidabrahams**

### CODE REVIEW

**Comment by nmohamed** [comment]
:palm_tree:

**Comment by shrutiyer** [comment]
:+1:

**Comment by aconsilvio** [comment]
🌲

**Comment by BrennaManning** [comment]
:+1:

**Comment by BrennaManning** [comment]
Merging!

**Pull request merged**
