### PR TITLE
Integrating student functions to login-auth

### PR DESCRIPTION
**Pull request by aconsilvio**

### CODE REVIEW

**Comment by nmohamed** [comment]
Why is this a pull request?

**Comment by davidabrahams** [comment]
So we can address merge conflicts on this branch before merging shrutis

**Comment by nmohamed** [comment]
Why not just pull into their branch and commit changes as they fix it? There isn't a need to make a PR for something that's verified

**Comment by davidabrahams** [comment]
Ya I guess this isn't technically proper use of PR but it's nice cuz it
makes it so everybody can see the conflicts

**Pull request closed without merging**
