### PR TITLE
EDIT: made sidebar absolute so that when you scroll the page the side…

### PR DESCRIPTION
**Pull request by davidabrahams**
…bar doesnt come with you

### CODE REVIEW

**Comment by nmohamed** [comment]
:palm_tree: :pager: :microphone:

**Comment by shrutiyer** [comment]
:+1:

**Comment by aconsilvio** [comment]
🚌 🚏 👍

**Comment by BrennaManning** [comment]
:+1:

**Comment by BrennaManning** [comment]
merging!

**Pull request merged**
